name: Run tests

on: [ push ]

jobs:

  test-leiningen:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@e73bf2b6435244b2c9c5c226ae5022d91d0ce702
        with:
          lein: 2.9.5

      - name: Run leiningen tests
        run: lein test
